### ISSUE TITLE
Wait for Page to load before querying

### ISSUE THREAD

**Issue by gshergill** [dharmafly/noodle#115]
Hi,

Not sure if this is possible, there is nothing documented around it. For us at least this is a very important feature. For example the following site http://pgatour.com/leaderboard.html requires some seconds before it loads the table with the data we need.

Is this missing from documentation or is it not possible? If the latter, it is a possible enhancement?

Thank you and Kind Regards,

Gary

**Comment by premasagar** [comment]
The problem is not the time delay, it is that the HTML source for that page does not contain the data that you want. The data is only loaded to clients via JavaScript. So, you are using Noodle to scrape the HTML and you are not finding the data.

I have experimented in the past with running Noodle in an instance of PhantomJS, allowing JavaScript to run and on completion, taking a snapshot of the HTML.
